name: bodabima
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core Widgets
  cupertino_icons: ^1.0.8
  
  # Backend & API
  supabase_flutter: ^2.8.0
  url_launcher: ^6.2.5
  
  # UI Components
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  
  # Localization
  intl: ^0.19.0
  intl_utils: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/l10n/app_en.arb
    - lib/l10n/app_sw.arb
    - assets/translations/en.json
    - assets/translations/sw.json
    - assets/icons/medical.png
    - assets/icons/home.png
    - assets/icons/travel.png
    - assets/icons/call-us.png
    - assets/icons/profile.png
    - assets/icons/emergency.png
    - assets/icons/logo.png
    - assets/icons/motor.png
    - assets/icons/car.png
    - assets/icons/ambulance.png
    - assets/icons/membership.png
    - assets/images/medical.jpg
    - assets/images/travel.jpg
    - assets/images/car.jpg
    - assets/images/home.png